export { default as ShanghaiSetup } from '~/components/shanghai/shanghai-setup';
export { default as ShanghaiReport } from '~/components/shanghai/shanghai-report';
export { default as ShanghaiScoreboard } from '~/components/shanghai/shanghai-scoreboard';
export { default as FlightIcon } from '~/components/shanghai/flight-icon';
export { default as ShanghaiMarks } from '~/components/shanghai/shanghai-marks';
export { default as ShanghaiKeypad } from '~/components/shanghai/shanghai-keypad';
export { default as ShanghaiPlayerCard } from '~/components/shanghai/shanghai-player-card';
export { default as ShanghaiRoundItem } from '~/components/shanghai/shanghai-round-item';
export { default as ShanghaiRules } from '~/components/shanghai/shanghai-rules';
