name: Coverage Badge

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to commit the changes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.11.0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Test
        run: pnpm test:ci

      - name: Install badgen
        run: pnpm i badgen

      - name: Generate Coverage Badge
        uses: ./.github/actions/generate-coverage-badge
        with:
          summary: ./coverage/coverage-summary.json

      - name: Copy badge to temp gh-pages, commit, and push
        run: |
          # set gh identity
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

          # clone gh-pages to a temp directory
          git fetch origin gh-pages
          git worktree add /tmp/gh-pages gh-pages

          # copy badge svg
          cp coverage.svg /tmp/gh-pages
          echo badge svg copied!

          # commit badge and push
          cd /tmp/gh-pages
          git add coverage.svg
          git commit -m "update coverage badge"
          echo badge svg committed!
          git push origin gh-pages

          # cleanup
          cd -
          git worktree remove /tmp/gh-pages
