name: Example Workflow

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.11.0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Run test coverage with summary report
        run: pnpm test:coverage --coverage.reporter=json-summary

      - name: Ensure test coverage threshold
        uses: ./.github/actions/example-action
        with:
          threshold: 90
