name: Example Workflow

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# concurrency:
#   group: ${{ github.event.pull_request.number }}
#   cancel-in-progress: false

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
      - name: Do custom action
        uses: ./.github/actions/example-action
