name: PR Check

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-head-ref-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.11.0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm test:ci

      - name: Upload coverage summary
        uses: actions/upload-artifact@v4
        with:
          name: head-ref-coverage-summary
          path: ./coverage/coverage-summary.json

  get-base-ref-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.11.0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Test base ref
        run: pnpm test:ci

      - name: Upload coverage summary
        uses: actions/upload-artifact@v4
        with:
          name: base-ref-coverage-summary
          path: ./coverage/coverage-summary.json

  compare-coverage:
    runs-on: ubuntu-latest
    needs: [test-head-ref-with-coverage, get-base-ref-coverage]
    steps:
      - name: Checkout base ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.11.0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Download code coverage report from base ref
        uses: actions/download-artifact@v4
        with:
          name: base-ref-coverage-summary
          path: coverage-summaries

      - name: Rename base ref coverage report
        run: mv ./coverage-summaries/coverage-summary.json ./coverage-summaries/base-ref-coverage-summary.json

      - name: Download code coverage report from head ref
        uses: actions/download-artifact@v4
        with:
          name: head-ref-coverage-summary
          path: coverage-summaries

      - name: Compare head and base ref coverage
        uses: ./.github/actions/compare-coverage
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 90
          base-summary: ./coverage-summaries/base-ref-coverage-summary.json
          head-summary: ./coverage-summaries/coverage-summary.json
